//
//  ExamplePresenter.swift
//  ManagerOfTasksCleanSwift
//
//  Created by Аркадий Варежкин on 21.10.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExamplePresentationLogic {
    func presentSomething(response: Example.Something.Response)
}

class ExamplePresenter: ExamplePresentationLogic {
    
    weak var viewController: ExampleDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Example.Something.Response) {
        let viewModel = Example.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
