//
//  ExampleInteractor.swift
//  ManagerOfTasksCleanSwift
//
//  Created by Аркадий Варежкин on 21.10.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExampleBusinessLogic {
    func doSomething(request: Example.Something.Request)
}

protocol ExampleDataStore {
    //var name: String { get set }
}

class ExampleInteractor: ExampleBusinessLogic, ExampleDataStore {
    
    var presenter: ExamplePresentationLogic?
    var worker: ExampleWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Example.Something.Request) {
        worker = ExampleWorker()
        worker?.doSomeWork()
        
        let response = Example.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
